### ISSUE TITLE
🚨 Notifications not showing on Android

### ISSUE THREAD

**Issue by Mustache-Games** [super-productivity/super-productivity#5376]
### Version Used

16.0.0 f-droid

### Expected Behavior

When I click the "Show Notification" in the API Test Plug-in I should receive a notification.

### Current Behavior

When I click the "Show Notification" in the API Test Plug-in nothing shows.
I made sure all notifications are allowed in the app settings and disabled battery optimization for Super Productivity.

<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/7fecb1df-0842-4bcd-9966-a1db004cbf40" />
<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/d6af5799-4cd5-42fd-9903-39157f1d08e6" />

### Steps to Reproduce

1. Enable "API Test Plug-in"
2. Go to "API Test Plug-in"
3. Click on "Show Notification"

https://github.com/user-attachments/assets/58f46b1f-d901-4ed4-9447-80caea81f1ae

### Can you reproduce this reliably?

Yes, I can reproduce it reliably.

### Console Output

```shell

```

**Comment by johannesjo** [comment]
This will hopefully be fixed with the next release.

**Comment by Mustache-Games** [comment]
Thanks a lot!

**Comment by Mustache-Games** [comment]
> This will hopefully be fixed with the next release.

Tested 16.2.0 play build (idk why fdroid build isn't available yet) and notifications still don't work.

**Comment by Mustache-Games** [comment]
BTW, normal reminders work which suggests that this a bug in the PluginAPI

**Comment by johannesjo** [comment]
Thanks @Mustache-Games ! Wasn't aware that this is limited to the plugin api at first. Thanks for the clarificaiton.

**Comment by Danie10** [comment]
In Aug 2026 I hear **an audible notification**, but there is no app focus at all, so I never get to see what the notification actually is. It keeps sounding the whole time I unlock the phone. As soon as I pull down the Android notifications menu, it goes silent. I have granted the app full permissions for all notifications related permissions. The biggest problem is I don't see what notification it is, and I can't snooze it for later or even mark it as done. My notifications are usually quite a few so there is no easy way to know that it is from Super Productivity, even though it shows in that list.

**Comment by Danie10** [comment]
@johannesjo what I've further noticed is, the problem seems to be when the screen is off. When I have the screen on, and I'm working on the phone, a notification does pop up with action buttons. I do already have permissions enabled to display on lock screen etc so I don't think it is permissions based.

**Comment by johannesjo** [comment]
@Mustache-Games sorry for the long silence here, and thanks for the clear repro video.

I have a plausible cause, but I need one thing from you to confirm it.

The Android app can run in two different shells: an older WebView one that loads the app over the network, and a newer offline-capable one. Upgraded installs that still carry old local data stay on the older shell. That shell has no bridge to the notification plugin, so the notification call silently does nothing — which would explain exactly what you saw: the plugin API's "Show Notification" does nothing, while normal reminders keep working, since those go through a separate native alarm path.

Could you check which one you're on? **Turn off wifi and mobile data, force-close the app, then open it.**

- If it doesn't load → you're on the older shell, and #10044 should fix this for you.
- If it loads fine → you're on the newer shell, and the cause is something else I haven't found yet.

#10044 is up either way since the silent drop is a real bug on its own, but I'd rather confirm before closing this out.

---

@Danie10 your report sounds like a separate problem — the notification fires and makes sound but never becomes visible while the screen is off. That's the reminder path rather than the plugin API, so it won't be addressed by the fix above. Could you open a new issue for it so it doesn't get lost?
