### ISSUE TITLE
💡Add powerful global task search with keyboard shortcut and advanced filtering

### ISSUE THREAD

**Issue by Tosko4** [super-productivity/super-productivity#5757]
### Problem Statement

I work with a large number of tasks and subtasks across multiple projects. As my task lists grow, it becomes increasingly difficult to quickly find a specific task without manually scrolling or navigating through multiple views.

The current search experience feels limited for power users: it’s not always immediately accessible, lacks advanced filtering, and does not clearly show task context (such as hierarchy or status) in the results. This slows down navigation and makes keyboard-driven workflows harder than they need to be.

### Possible Solution

Introduce a global, always-accessible search experience with both mouse and keyboard support.

Suggested behavior and features:

- A search entry that is always visible in the top bar (desktop app and web), instead of the sidebar at the very bottom with settings button etc.
- Clicking this search entry opens a search popup/modal
- A global keyboard shortcut (e.g. Ctrl+K or Ctrl+Shift+F) to instantly open the same search popup

Within the search popup:

- Real-time search while typing
- Support for filtering by:
- project
- tag(s)
- task status (open / closed)
- wildcard or partial matches in title and description
- Clear visual indication of whether a task is open or closed
- Option to include or exclude closed tasks

For subtasks in search results:

- Display the full hierarchy when a subtask is matched
- Show the parent task, with the matching subtask indented underneath
- This provides immediate context without needing to open the task first

Optional but valuable enhancements:

- Keyboard navigation (arrow keys to move through results)
- Press Enter to open or focus the selected task
- Clean, uncluttered result layout optimized for quick scanning

### Describe alternatives you've considered

Manually navigating through project views, filters, or long task lists.
Using existing search functionality, which works for basic cases but lacks visibility, context, and advanced filtering needed for larger task sets.

### Additional context

This feature would significantly improve productivity for users managing many small tasks, deep task hierarchies, or multiple parallel projects, especially those who prefer keyboard-driven workflows.

**Comment by blefuscu** [comment]
This is my **community-feedback**: duplicate/merge this with #5449 , somewhat related to #5476  and possibly also #4646 / #4621 

I agree that a powerful search facility is seriously needed.

**Comment by YashodharChavan** [comment]
Yes with powerful search I think we should also provide filters like date range selection, day selection, or any useful one. Mere search bar seems to be not enough...

**Comment by Tosko4** [comment]
@blefuscu, I agree with you; there is a resemblance. Would it help @johannesjo if we merged them into one?

And what @YashodharChavan suggested is good as well. I can add it to my list?

**Comment by anikaglobals-stack** [comment]
Thanks you guys! I completely agree with your perspective. I hope Global Search will be implemented in the near future, as it is essential for everyone. However, I am still unable to locate a folder by name.
